export enum maritalStatus {
  SINGLE = "SINGLE",
  MARRIED = "MARRIED",
  DIVORCED = "DIVORCED",
  SEPARATED = "SEPARATED",
  COHABITATING = "COHABITATING",
  WIDOWED = "WIDOWED",
  WIDOWER = "WIDOWER"
}